//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DomainModel.DTO.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Unitprice { get; set; }
        public int Number { get; set; }
        public int Discount { get; set; }
        public string Name { get; set; }
        public int All { get; set; }
        public int id { get; set; }
        public string Ref_Person { get; set; }
    }
}
